name: Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Generate Documentation
      run: ./gradlew dokkaHtml
    - name: Move documentation to the correct folder
      run: |
          rm -rf docs
          mv app/build/dokka/html docs
          git add docs
          git commit -m "Update Documentation"
          git push

